


spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 20
  
  devtools:
    livereload.enabled: true
  
  servlet.multipart:
    max-file-size: 5GB
    max-request-size: 5GB
  
  
##################################################
json:
  test:
    file: src/main/resources/json/test.json
    file01: src/main/resources/json/test.json
    file02: src/main/resources/json/test.json
    file03: src/main/resources/json/test.json
    file04: src/main/resources/json/test.json
    file05: src/main/resources/json/test.json
    file06: src/main/resources/json/test.json
    file07: src/main/resources/json/test07.json
  packet:
    file: src/main/resources/table/table_packet.json

yaml:
  test:
    file05: src/main/resources/json/test.yaml

##################################################
####################################################
spring.profiles.active: local-http

---
spring:
  profiles: local-http
  
server.port: 8083

---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey





