

spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 20
  
  devtools:
    livereload.enabled: true
  
  servlet.multipart:
    max-file-size: 5GB
    max-request-size: 5GB
  
  
########################################################
json:
  test:
    file01: src/main/resources/json/test01.json
    file02: src/main/resources/json/test02.json
    file03: src/main/resources/json/test03.json
    auth-req.file:  src/main/resources/json/auth_req.json
    
  out:
    file03: src/main/resources/json/test03_out.json
  packet:
    file01: src/main/resources/table/table_packet.json

  group:
    path: src/main/resources/group
    out:
      file: src/main/resources/table/table_group.json

  meta:
    path: src/main/resources/meta
    out:
      file: src/main/resources/table/table_meta.json
  
  data:
    file101: src/main/resources/json/auth_req.json
    file102: src/main/resources/json/auth_res.json
    # file201: src/main/resources/json/detail_req.json
    file202: src/main/resources/json/detail_res.json
    
yaml:
  test:
    file01: src/main/resources/json/test01.yaml
    file02: src/main/resources/json/test02.yaml
    file03: src/main/resources/json/test03.yaml


########################################################
########################################################
spring.profiles.active: local-http

---
spring:
  profiles: local-http
  
server.port: 8083

---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey









