


spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 20
  
  devtools.livereload.enabled: true
  
####################################################
spring.servlet.multipart:
  max-file-size: 5GB
  max-request-size: 5GB
  
####################################################
json:
  files:
  - src/main/resources/json/auth_req.json
  - src/main/resources/json/auth_res.json
  - src/main/resources/json/list_req.json
  - src/main/resources/json/list_res.json
  - src/main/resources/json/detail_req.json
  - src/main/resources/json/detail_res.json
  - src/main/resources/json/validate_req.json
  - src/main/resources/json/validate_res.json
  - src/main/resources/json/commit_req.json
  - src/main/resources/json/commit_res.json
  - src/main/resources/json/callback_req.json
  - src/main/resources/json/callback_res.json
  auth:
    req-file: src/main/resources/json/auth_req.json
    res-file: src/main/resources/json/auth_res.json
  list:
    req-file: src/main/resources/json/list_req.json
    res-file: src/main/resources/json/list_res.json
  detail:
    req-file: src/main/resources/json/detail_req.json
    res-file: src/main/resources/json/detail_res.json
  validate:
    req-file: src/main/resources/json/validate_req.json
    res-file: src/main/resources/json/validate_res.json
  commit:
    req-file: src/main/resources/json/commit_req.json
    res-file: src/main/resources/json/commit_res.json
  callback:
    req-file: src/main/resources/json/callback_req.json
    res-file: src/main/resources/json/callback_res.json
  test:
    file: src/main/resources/json/test.json

####################################################
security.ignored: /**
security.basic.enabled: false
management.security.enabled: false
spring.security.enabled: false

####################################################
####################################################
spring.profiles.active: local-http

---
spring:
  profiles: local-http
  
server.port: 8080

---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey






